// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1-devel
// 	protoc        v3.21.5
// source: proto/deploymentConfigurations/security/Saml.proto

package security

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Configuration for the clouddriver microservice.
type Saml struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled           bool   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	MetadataRemote    string `protobuf:"bytes,2,opt,name=metadataRemote,proto3" json:"metadataRemote,omitempty"`
	IssuerId          string `protobuf:"bytes,3,opt,name=issuerId,proto3" json:"issuerId,omitempty"`
	KeyStore          string `protobuf:"bytes,4,opt,name=keyStore,proto3" json:"keyStore,omitempty"`
	KeyStorePassword  string `protobuf:"bytes,5,opt,name=keyStorePassword,proto3" json:"keyStorePassword,omitempty"`
	KeyStoreAliasName string `protobuf:"bytes,6,opt,name=keyStoreAliasName,proto3" json:"keyStoreAliasName,omitempty"`
	ServiceAddress    string `protobuf:"bytes,7,opt,name=serviceAddress,proto3" json:"serviceAddress,omitempty"`
}

func (x *Saml) Reset() {
	*x = Saml{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_deploymentConfigurations_security_Saml_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Saml) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Saml) ProtoMessage() {}

func (x *Saml) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deploymentConfigurations_security_Saml_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Saml.ProtoReflect.Descriptor instead.
func (*Saml) Descriptor() ([]byte, []int) {
	return file_proto_deploymentConfigurations_security_Saml_proto_rawDescGZIP(), []int{0}
}

func (x *Saml) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Saml) GetMetadataRemote() string {
	if x != nil {
		return x.MetadataRemote
	}
	return ""
}

func (x *Saml) GetIssuerId() string {
	if x != nil {
		return x.IssuerId
	}
	return ""
}

func (x *Saml) GetKeyStore() string {
	if x != nil {
		return x.KeyStore
	}
	return ""
}

func (x *Saml) GetKeyStorePassword() string {
	if x != nil {
		return x.KeyStorePassword
	}
	return ""
}

func (x *Saml) GetKeyStoreAliasName() string {
	if x != nil {
		return x.KeyStoreAliasName
	}
	return ""
}

func (x *Saml) GetServiceAddress() string {
	if x != nil {
		return x.ServiceAddress
	}
	return ""
}

type SamlUserInfoMapping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email          string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Firstname      string `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname       string `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Username       string `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Roles          string `protobuf:"bytes,5,opt,name=roles,proto3" json:"roles,omitempty"`
	RolesDelimiter string `protobuf:"bytes,6,opt,name=rolesDelimiter,proto3" json:"rolesDelimiter,omitempty"`
}

func (x *SamlUserInfoMapping) Reset() {
	*x = SamlUserInfoMapping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_deploymentConfigurations_security_Saml_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SamlUserInfoMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SamlUserInfoMapping) ProtoMessage() {}

func (x *SamlUserInfoMapping) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deploymentConfigurations_security_Saml_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SamlUserInfoMapping.ProtoReflect.Descriptor instead.
func (*SamlUserInfoMapping) Descriptor() ([]byte, []int) {
	return file_proto_deploymentConfigurations_security_Saml_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SamlUserInfoMapping) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SamlUserInfoMapping) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *SamlUserInfoMapping) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *SamlUserInfoMapping) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SamlUserInfoMapping) GetRoles() string {
	if x != nil {
		return x.Roles
	}
	return ""
}

func (x *SamlUserInfoMapping) GetRolesDelimiter() string {
	if x != nil {
		return x.RolesDelimiter
	}
	return ""
}

var File_proto_deploymentConfigurations_security_Saml_proto protoreflect.FileDescriptor

var file_proto_deploymentConfigurations_security_Saml_proto_rawDesc = []byte{
	0x0a, 0x32, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2f, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x2f, 0x53, 0x61, 0x6d, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x65, 0x63, 0x75,
	0x72, 0x69, 0x74, 0x79, 0x22, 0xc0, 0x03, 0x0a, 0x04, 0x53, 0x61, 0x6d, 0x6c, 0x12, 0x18, 0x0a,
	0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6b,
	0x65, 0x79, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6b,
	0x65, 0x79, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x6b, 0x65, 0x79, 0x53, 0x74,
	0x6f, 0x72, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x6b, 0x65, 0x79, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x12, 0x2c, 0x0a, 0x11, 0x6b, 0x65, 0x79, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x41,
	0x6c, 0x69, 0x61, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11,
	0x6b, 0x65, 0x79, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x1a, 0xbb, 0x01, 0x0a, 0x0f, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6c,
	0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x12,
	0x26, 0x0a, 0x0e, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x44, 0x65, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65,
	0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x44, 0x65,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x42, 0x2a, 0x5a, 0x28, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x2f, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x73, 0x65, 0x63, 0x75, 0x72,
	0x69, 0x74, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_deploymentConfigurations_security_Saml_proto_rawDescOnce sync.Once
	file_proto_deploymentConfigurations_security_Saml_proto_rawDescData = file_proto_deploymentConfigurations_security_Saml_proto_rawDesc
)

func file_proto_deploymentConfigurations_security_Saml_proto_rawDescGZIP() []byte {
	file_proto_deploymentConfigurations_security_Saml_proto_rawDescOnce.Do(func() {
		file_proto_deploymentConfigurations_security_Saml_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_deploymentConfigurations_security_Saml_proto_rawDescData)
	})
	return file_proto_deploymentConfigurations_security_Saml_proto_rawDescData
}

var file_proto_deploymentConfigurations_security_Saml_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_deploymentConfigurations_security_Saml_proto_goTypes = []interface{}{
	(*Saml)(nil),                // 0: proto.security.Saml
	(*SamlUserInfoMapping)(nil), // 1: proto.security.Saml.userInfoMapping
}
var file_proto_deploymentConfigurations_security_Saml_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_deploymentConfigurations_security_Saml_proto_init() }
func file_proto_deploymentConfigurations_security_Saml_proto_init() {
	if File_proto_deploymentConfigurations_security_Saml_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_deploymentConfigurations_security_Saml_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Saml); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_deploymentConfigurations_security_Saml_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SamlUserInfoMapping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_deploymentConfigurations_security_Saml_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_deploymentConfigurations_security_Saml_proto_goTypes,
		DependencyIndexes: file_proto_deploymentConfigurations_security_Saml_proto_depIdxs,
		MessageInfos:      file_proto_deploymentConfigurations_security_Saml_proto_msgTypes,
	}.Build()
	File_proto_deploymentConfigurations_security_Saml_proto = out.File
	file_proto_deploymentConfigurations_security_Saml_proto_rawDesc = nil
	file_proto_deploymentConfigurations_security_Saml_proto_goTypes = nil
	file_proto_deploymentConfigurations_security_Saml_proto_depIdxs = nil
}
