// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1-devel
// 	protoc        v3.21.5
// source: proto/deploymentConfigurations/metricStores/Stackdriver.proto

package metricStores

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Configuration for the clouddriver microservice.
type Stackdriver struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled         bool   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Project         string `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	Zone            string `protobuf:"bytes,3,opt,name=zone,proto3" json:"zone,omitempty"`
	CredentialsPath string `protobuf:"bytes,4,opt,name=credentials_path,json=credentialsPath,proto3" json:"credentials_path,omitempty"`
}

func (x *Stackdriver) Reset() {
	*x = Stackdriver{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_deploymentConfigurations_metricStores_Stackdriver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stackdriver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stackdriver) ProtoMessage() {}

func (x *Stackdriver) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deploymentConfigurations_metricStores_Stackdriver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stackdriver.ProtoReflect.Descriptor instead.
func (*Stackdriver) Descriptor() ([]byte, []int) {
	return file_proto_deploymentConfigurations_metricStores_Stackdriver_proto_rawDescGZIP(), []int{0}
}

func (x *Stackdriver) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Stackdriver) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *Stackdriver) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *Stackdriver) GetCredentialsPath() string {
	if x != nil {
		return x.CredentialsPath
	}
	return ""
}

var File_proto_deploymentConfigurations_metricStores_Stackdriver_proto protoreflect.FileDescriptor

var file_proto_deploymentConfigurations_metricStores_Stackdriver_proto_rawDesc = []byte{
	0x0a, 0x3d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x2f, 0x53, 0x74,
	0x61, 0x63, 0x6b, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x73, 0x22, 0x80, 0x01, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x64, 0x72, 0x69,
	0x76, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x7a, 0x6f, 0x6e, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x7a, 0x6f, 0x6e, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x63,
	0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61,
	0x6c, 0x73, 0x50, 0x61, 0x74, 0x68, 0x42, 0x2e, 0x5a, 0x2c, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x2f, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_deploymentConfigurations_metricStores_Stackdriver_proto_rawDescOnce sync.Once
	file_proto_deploymentConfigurations_metricStores_Stackdriver_proto_rawDescData = file_proto_deploymentConfigurations_metricStores_Stackdriver_proto_rawDesc
)

func file_proto_deploymentConfigurations_metricStores_Stackdriver_proto_rawDescGZIP() []byte {
	file_proto_deploymentConfigurations_metricStores_Stackdriver_proto_rawDescOnce.Do(func() {
		file_proto_deploymentConfigurations_metricStores_Stackdriver_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_deploymentConfigurations_metricStores_Stackdriver_proto_rawDescData)
	})
	return file_proto_deploymentConfigurations_metricStores_Stackdriver_proto_rawDescData
}

var file_proto_deploymentConfigurations_metricStores_Stackdriver_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_deploymentConfigurations_metricStores_Stackdriver_proto_goTypes = []interface{}{
	(*Stackdriver)(nil), // 0: proto.metricStores.Stackdriver
}
var file_proto_deploymentConfigurations_metricStores_Stackdriver_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_deploymentConfigurations_metricStores_Stackdriver_proto_init() }
func file_proto_deploymentConfigurations_metricStores_Stackdriver_proto_init() {
	if File_proto_deploymentConfigurations_metricStores_Stackdriver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_deploymentConfigurations_metricStores_Stackdriver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stackdriver); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_deploymentConfigurations_metricStores_Stackdriver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_deploymentConfigurations_metricStores_Stackdriver_proto_goTypes,
		DependencyIndexes: file_proto_deploymentConfigurations_metricStores_Stackdriver_proto_depIdxs,
		MessageInfos:      file_proto_deploymentConfigurations_metricStores_Stackdriver_proto_msgTypes,
	}.Build()
	File_proto_deploymentConfigurations_metricStores_Stackdriver_proto = out.File
	file_proto_deploymentConfigurations_metricStores_Stackdriver_proto_rawDesc = nil
	file_proto_deploymentConfigurations_metricStores_Stackdriver_proto_goTypes = nil
	file_proto_deploymentConfigurations_metricStores_Stackdriver_proto_depIdxs = nil
}
