// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1-devel
// 	protoc        v3.21.5
// source: proto/deploymentConfigurations/ci/Wercker.proto

package ci

import (
	permissions "github.com/austinthao5/golang_proto_test/config/deploymentConfigurations/permissions"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Configuration for the clouddriver microservice.
type Wercker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled bool              `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Masters []*WerckerMasters `protobuf:"bytes,2,rep,name=masters,proto3" json:"masters,omitempty"`
}

func (x *Wercker) Reset() {
	*x = Wercker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_deploymentConfigurations_ci_Wercker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Wercker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wercker) ProtoMessage() {}

func (x *Wercker) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deploymentConfigurations_ci_Wercker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wercker.ProtoReflect.Descriptor instead.
func (*Wercker) Descriptor() ([]byte, []int) {
	return file_proto_deploymentConfigurations_ci_Wercker_proto_rawDescGZIP(), []int{0}
}

func (x *Wercker) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Wercker) GetMasters() []*WerckerMasters {
	if x != nil {
		return x.Masters
	}
	return nil
}

type WerckerMasters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Permission *permissions.Permissions `protobuf:"bytes,2,opt,name=permission,proto3" json:"permission,omitempty"`
	Address    string                   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	User       string                   `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	Token      string                   `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *WerckerMasters) Reset() {
	*x = WerckerMasters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_deploymentConfigurations_ci_Wercker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WerckerMasters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WerckerMasters) ProtoMessage() {}

func (x *WerckerMasters) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deploymentConfigurations_ci_Wercker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WerckerMasters.ProtoReflect.Descriptor instead.
func (*WerckerMasters) Descriptor() ([]byte, []int) {
	return file_proto_deploymentConfigurations_ci_Wercker_proto_rawDescGZIP(), []int{1}
}

func (x *WerckerMasters) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WerckerMasters) GetPermission() *permissions.Permissions {
	if x != nil {
		return x.Permission
	}
	return nil
}

func (x *WerckerMasters) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *WerckerMasters) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *WerckerMasters) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_proto_deploymentConfigurations_ci_Wercker_proto protoreflect.FileDescriptor

var file_proto_deploymentConfigurations_ci_Wercker_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2f, 0x63, 0x69, 0x2f, 0x57, 0x65, 0x72, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x69, 0x1a, 0x3c, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x70, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x57, 0x0a, 0x07, 0x57, 0x65, 0x72,
	0x63, 0x6b, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x32,
	0x0a, 0x07, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x69, 0x2e, 0x57, 0x65, 0x72, 0x63, 0x6b,
	0x65, 0x72, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x73, 0x52, 0x07, 0x6d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x73, 0x22, 0xa8, 0x01, 0x0a, 0x0e, 0x57, 0x65, 0x72, 0x63, 0x6b, 0x65, 0x72, 0x4d, 0x61,
	0x73, 0x74, 0x65, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3e, 0x0a, 0x0a, 0x70, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0a, 0x70,
	0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x24, 0x5a,
	0x22, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2f, 0x63, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_deploymentConfigurations_ci_Wercker_proto_rawDescOnce sync.Once
	file_proto_deploymentConfigurations_ci_Wercker_proto_rawDescData = file_proto_deploymentConfigurations_ci_Wercker_proto_rawDesc
)

func file_proto_deploymentConfigurations_ci_Wercker_proto_rawDescGZIP() []byte {
	file_proto_deploymentConfigurations_ci_Wercker_proto_rawDescOnce.Do(func() {
		file_proto_deploymentConfigurations_ci_Wercker_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_deploymentConfigurations_ci_Wercker_proto_rawDescData)
	})
	return file_proto_deploymentConfigurations_ci_Wercker_proto_rawDescData
}

var file_proto_deploymentConfigurations_ci_Wercker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_deploymentConfigurations_ci_Wercker_proto_goTypes = []interface{}{
	(*Wercker)(nil),                 // 0: proto.ci.Wercker
	(*WerckerMasters)(nil),          // 1: proto.ci.WerckerMasters
	(*permissions.Permissions)(nil), // 2: proto.permissions.Permissions
}
var file_proto_deploymentConfigurations_ci_Wercker_proto_depIdxs = []int32{
	1, // 0: proto.ci.Wercker.masters:type_name -> proto.ci.WerckerMasters
	2, // 1: proto.ci.WerckerMasters.permission:type_name -> proto.permissions.Permissions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_deploymentConfigurations_ci_Wercker_proto_init() }
func file_proto_deploymentConfigurations_ci_Wercker_proto_init() {
	if File_proto_deploymentConfigurations_ci_Wercker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_deploymentConfigurations_ci_Wercker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Wercker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_deploymentConfigurations_ci_Wercker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WerckerMasters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_deploymentConfigurations_ci_Wercker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_deploymentConfigurations_ci_Wercker_proto_goTypes,
		DependencyIndexes: file_proto_deploymentConfigurations_ci_Wercker_proto_depIdxs,
		MessageInfos:      file_proto_deploymentConfigurations_ci_Wercker_proto_msgTypes,
	}.Build()
	File_proto_deploymentConfigurations_ci_Wercker_proto = out.File
	file_proto_deploymentConfigurations_ci_Wercker_proto_rawDesc = nil
	file_proto_deploymentConfigurations_ci_Wercker_proto_goTypes = nil
	file_proto_deploymentConfigurations_ci_Wercker_proto_depIdxs = nil
}
